version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${POSTGRES_HOST}

  # nestjs:
  #   build: 
  #     context: ./back
  #     dockerfile: ./Dockerfile
  #   image: back_nest
  #   environment: 
  #     DB_TYPE: ${DB_TYPE}
  #     POSTGRES_HOST: ${POSTGRES_HOST}
  #     POSTGRES_USER: ${DATABASE_USER}
  #     POSTGRES_PASS: ${DATABASE_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #     HOST_IP: ${HOST_IP}
  #   ports: 
  #     - "3000:3000"
  #   container_name: nest-trans
  #   depends_on: 
  #     - db

  # vuejs:
  #   build: 
  #     context: ./front
  #     dockerfile: ./Dockerfile
  #   image: front_vue
  #   # environment: 
  #   #   - HOST_IP=${HOST_IP}
  #   #   - AUTH=${AUTH}
  #   # env_file:
  #   #   -  ./.env
  #   ports: 
  #     - "8080:8080"
  #   container_name: vue-trans
